### ISSUE TITLE
Import SystemRDLExporter in __init__.py

### ISSUE THREAD

**Issue by howardtr** [SystemRDL/PeakRDL-systemrdl#1]
Hi,

I needed to add the following lines to __init__.py to get SystemRDLExporter to work like the other Exporter tools. 

```
from .__about__ import __version__

from .exporter import SystemRDLExporter
```

**Comment by amykyta3** [comment]
Will add. Thanks!
I didnt realize I was following that convention in all the other tools. Makes sense to normalize it though.

**Comment by amykyta3** [comment]
Will be included in the next release

**Comment by howardtr** [comment]
Thank you! :)
